#!/bin/zsh

sus() {
    #i3lock -c 222222
    #i3lock -i ~/.config/i3/scripts/lockscreen/lockscreen.png -t
    systemctl suspend
    slock
}


cmd=$(echo -e "lock\nlogout\nsuspend\nhibernate\nreboot\nshutdown" | dmenu -b)


case "$cmd" in
    lock)
        slock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sus
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
